apiVersion: v1
kind: Service
metadata:
  namespace: mayday
  labels:
    app: db
  name: db
spec:
  type: LoadBalancer
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: db
