apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayday
#  labels:
#    app: mayday-api
  namespace: mayday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayday
  template:
    metadata:
      labels:
        app: mayday
    spec:
      containers:
        - name: mayday
          image: mayday:latest
          imagePullPolicy: Never
          ports:
            - name: mayday
              containerPort: 8202
---
apiVersion: v1
kind: Service
metadata:
  name: mayday-entrypoint
  namespace: mayday
spec:
  type: LoadBalancer
#  type: NodePort
  selector:
    app: mayday
  ports:
    - port: 8202
      targetPort: 8202
#      nodePort: 30081
