apiVersion: v1
kind: Service
metadata:
  namespace: mayday
  labels:
    app: mayday-backend
  name: mayday-backend
spec:
  type: LoadBalancer
  ports:
    - name: "8725"
      port: 8725
      targetPort: 8725
  selector:
    app: mayday-backend
