apiVersion: v1
kind: Service
metadata:
  namespace: mayday
  labels:
    app: mayday-db
  name: mayday-db
spec:
  type: LoadBalancer
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3306
  selector:
    app: mayday-db
