apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mayday
  name: mayday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayday
  template:
    metadata:
      labels:
        app: mayday
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env
            - name: MARIADB_APP_PASS
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_APP_PASS
                  name: env
            - name: MARIADB_DB
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_DB
                  name: env
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_HOST
                  name: env
            - name: MARIADB_PASS
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_PASS
                  name: env
            - name: MARIADB_PORT
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_PORT
                  name: env
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_USER
                  name: env
          image: mayday:latest
          imagePullPolicy: Never
          name: mayday
      hostname: mayday
      restartPolicy: Always
