apiVersion: v1
kind: Service
metadata:
  namespace: mayday
  labels:
    app: mayday-frontend
  name: mayday-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
  selector:
    app: mayday-frontend
