volumes:
  data:
services:
  mayday:
#    network_mode: "host"
    container_name: mayday
    hostname: mayday
    restart: always
    build:
      tags:
        - mayday:latest
      context: ../
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - "8202:8202"
  mayday-fe:
#    network_mode: "host"
    container_name: mayday-fe
    hostname: mayday-fe
    restart: always
    build:
      tags:
        - mayday-fe:latest
      context: ../
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_PORT: $FRONTEND_PORT
    ports:
      - "$FRONTEND_PORT:3000"
  db:
    container_name: mayday-db
    image: mariadb:latest
    # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/#mariadb_user-mysql_user-mariadb_password_hash-mariadb_password-mysql_password
    restart: always
    build:
      tags:
        - mayday-db:latest
      context: ../
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    environment:
      MARIADB_USER: maydayapp
      MARIADB_PASSWORD: $MARIADB_APP_PASS
      MARIADB_ROOT_PASSWORD: $MARIADB_PASS
      MARIADB_DATABASE: $MARIADB_DB
    ports:
      - "$MARIADB_PORT:3306"
