volumes:
  data:
services:
  mayday-backend:
#    network_mode: "host"
    container_name: mayday-backend
    hostname: mayday-backend
    restart: always
    image: mayday-backend
    pull_policy: never
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - "8202:8202"
  mayday-frontend:
#    network_mode: "host"
    container_name: mayday-frontend
    hostname: mayday-frontend
    image: mayday-frontend
    pull_policy: never
    restart: always
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_PORT: $FRONTEND_PORT
    ports:
      - "$FRONTEND_PORT:3000"
  mayday-db:
    container_name: mayday-db
    hostname: mayday-db
    image: mariadb:latest
#    image: mayday-db
#    pull_policy: never
    # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/#mariadb_user-mysql_user-mariadb_password_hash-mariadb_password-mysql_password
    restart: always
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    environment:
      MARIADB_USER: maydayapp
      MARIADB_PASSWORD: $MARIADB_APP_PASS
      MARIADB_ROOT_PASSWORD: $MARIADB_PASS
      MARIADB_DATABASE: $MARIADB_DB
    ports:
      - "$MARIADB_PORT:3306"
